[package]
name = "open-reader-desktop"
version = "0.1.0"
description = "A Windows-first open-source desktop reader"
authors = ["TttXxx36"]
edition = "2021"

[lib]
name = "open_reader_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
base64 = "0.22"
tauri-build = { version = "2" }

[dependencies]
tauri = { version = "2" }
encoding_rs = "0.8"
rusqlite = { version = "0.32", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
zip = "2"
